services:
  - type: web
    name: twilio-ivr-ai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 5000
    autoDeploy: true
